# 设置请求前缀
server:
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Shanghai
    username: root
    password: gsll
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用阿里巴巴druid数据源，默认使用自带的
    type: com.alibaba.druid.pool.DruidDataSource


# mybatis配置
mybatis-plus:
  # 配置别名需要扫描的包
  type-aliases-package: cn.hellomyheart.kataba.entity
  # 引入映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志在控制台显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# pagehelper


#自定义配置
kataba:
  passkey: Ch5CX73J5pUlW+/sK11VDA==
