-- MySQL Script generated by MySQL Workbench
-- 2020年10月22日 星期四 15时21分21秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `email` VARCHAR(200) NULL COMMENT '邮箱',
  `password` VARCHAR(200) NULL COMMENT '密码',
  `nickname` VARCHAR(80) NULL COMMENT '昵称',
  `icon` VARCHAR(255) NULL COMMENT '头像',
  `status` INT NULL COMMENT '标志位 0 未激活，1激活',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `c_id` INT NULL COMMENT '公司id',
  `name` VARCHAR(200) NULL COMMENT '职位名',
  `decription` VARCHAR(200) NULL COMMENT '职位描述',
  `skill` VARCHAR(200) NULL COMMENT '技能&要求',
  `salary` VARCHAR(45) NULL COMMENT '预期工资',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '职位表';


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL COMMENT '用户id',
  `name` VARCHAR(200) NULL COMMENT '公司名',
  `address` VARCHAR(200) NULL COMMENT '公司地址',
  `decription` VARCHAR(200) NULL COMMENT '公司简介',
  `status` INT NULL COMMENT '状态（1.正常，2.删除）',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '公司表';


-- -----------------------------------------------------
-- Table `mydb`.`resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resume` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `u_id` INT NULL COMMENT '用户id',
  `address` VARCHAR(200) NULL COMMENT '简历地址',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '简历表';


-- -----------------------------------------------------
-- Table `mydb`.`recruit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recruit` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `p_id` INT NULL COMMENT '职位id',
  `num` INT NULL COMMENT '招聘人数',
  `address` VARCHAR(200) NULL COMMENT '工作地点',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '招聘表';


-- -----------------------------------------------------
-- Table `mydb`.`interview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interview` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `r_id` INT NULL COMMENT '招聘id',
  `u_id` INT NULL COMMENT '用户id',
  `address` VARCHAR(200) NULL COMMENT '面试地址',
  `i_time` DATETIME NULL COMMENT '面试时间',
  `status` INT NULL COMMENT '状态（1.邀请面试2.确认面试 3.面试结束 4.面试失败（未面试） ）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '面试表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
