-- MySQL Script generated by MySQL Workbench
-- 2020年10月30日 星期五 22时19分04秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_boss
-- -----------------------------------------------------
-- 仿boss直聘项目

-- -----------------------------------------------------
-- Schema db_boss
--
-- 仿boss直聘项目
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_boss` DEFAULT CHARACTER SET utf8 ;
USE `db_boss` ;

-- -----------------------------------------------------
-- Table `db_boss`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `email` VARCHAR(200) NULL COMMENT '邮箱',
  `password` VARCHAR(200) NULL COMMENT '密码',
  `nickname` VARCHAR(80) NULL COMMENT '昵称',
  `icon` VARCHAR(255) NULL COMMENT '头像',
  `status` INT NULL COMMENT '标志位 0 未激活，1求职者，2招聘者',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_boss`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `c_id` INT NULL COMMENT '公司id',
  `ri_id` INT NULL COMMENT '发布者id(招聘者id)',
  `name` VARCHAR(200) NULL COMMENT '职位名',
  `decription` VARCHAR(200) NULL COMMENT '职位描述',
  `skill` VARCHAR(200) NULL COMMENT '技能&要求',
  `salary` VARCHAR(45) NULL COMMENT '预期工资',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  `status` VARCHAR(45) NULL COMMENT '状态（0.删除 1.正常）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '职位表';


-- -----------------------------------------------------
-- Table `db_boss`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL COMMENT '用户id',
  `name` VARCHAR(200) NULL COMMENT '公司名',
  `address` VARCHAR(200) NULL COMMENT '公司地址',
  `decription` VARCHAR(200) NULL COMMENT '公司简介',
  `status` INT NULL COMMENT '状态（1.正常，0.删除）',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '公司表';


-- -----------------------------------------------------
-- Table `db_boss`.`resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`resume` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `a_id` INT NULL COMMENT '应聘者id',
  `address` VARCHAR(200) NULL COMMENT '简历地址',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '简历表';


-- -----------------------------------------------------
-- Table `db_boss`.`recruit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`recruit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL,
  `createtime` DATETIME NULL,
  `type` VARCHAR(45) NULL COMMENT '类型 add、update、delete',
  `decription` VARCHAR(200) NULL COMMENT '详情描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '招聘信息日志表';


-- -----------------------------------------------------
-- Table `db_boss`.`interview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`interview` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `ri_id` INT NULL COMMENT '招聘id',
  `a_id` INT NULL COMMENT '应聘者id',
  `address` VARCHAR(200) NULL COMMENT '面试地址',
  `i_time` DATETIME NULL COMMENT '面试时间',
  `flag` INT NULL COMMENT '状态（1.邀请面试2.确认面试 3.面试结束 4.面试失败（未面试） 5.拒绝面试）',
  `status` INT NULL COMMENT '状态0.删除1.正常',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '面试表';


-- -----------------------------------------------------
-- Table `db_boss`.`provence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`provence` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `p_name` VARCHAR(200) NULL COMMENT '省名字',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '省表';


-- -----------------------------------------------------
-- Table `db_boss`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `p_id` INT NULL COMMENT '省id',
  `c_name` VARCHAR(200) NULL COMMENT '市名字',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '市表';


-- -----------------------------------------------------
-- Table `db_boss`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`district` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `c_id` INT NULL COMMENT '市id',
  `d_name` VARCHAR(200) NULL COMMENT '区名字',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '区表';


-- -----------------------------------------------------
-- Table `db_boss`.`address_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`address_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `d_id` INT NULL COMMENT '区id',
  `address_info` VARCHAR(200) NULL COMMENT '详细地址',
  `status` INT NULL COMMENT '状态 0.删除1.正常',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '地址详情表';


-- -----------------------------------------------------
-- Table `db_boss`.`applyInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`applyInfo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `u_id` INT NULL,
  `sp_id` INT NULL COMMENT '期望职位（系统职位3id）',
  `status` INT NULL COMMENT '状态（0.删除，1.正常）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '应聘者';


-- -----------------------------------------------------
-- Table `db_boss`.`system_position_one`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`system_position_one` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `sp_name` VARCHAR(200) NULL COMMENT '系统职位名',
  `status` INT NULL COMMENT '状态0.删除，1.正常',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '系统职位1';


-- -----------------------------------------------------
-- Table `db_boss`.`system_position_two`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`system_position_two` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `sp_name` VARCHAR(200) NULL COMMENT '系统职位名',
  `spo_id` INT NULL COMMENT '一级职位的id',
  `status` INT NULL COMMENT '状态0.删除，1.正常',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '系统职位2';


-- -----------------------------------------------------
-- Table `db_boss`.`system_position_three`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`system_position_three` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `sp_name` VARCHAR(200) NULL COMMENT '系统职位名',
  `spt_id` INT NULL COMMENT '二级职位的id',
  `status` INT NULL COMMENT '状态0.删除，1.正常',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '系统职位3';


-- -----------------------------------------------------
-- Table `db_boss`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`authority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `a_id` INT NULL COMMENT '应聘者id',
  `r_id` INT NULL COMMENT '简历ID',
  `ri_id` INT NULL COMMENT '招聘者',
  `status` INT NULL COMMENT 'status(状态0，请求(redis)1，确认2.拒绝)',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '简历权限表';


-- -----------------------------------------------------
-- Table `db_boss`.`recruit_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`recruit_position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ri_id` INT NULL COMMENT '招聘者id',
  `rp_name` VARCHAR(200) NULL COMMENT '招聘者职位职位名',
  `createtime` DATETIME NULL,
  `updatetime` DATETIME NULL,
  `status` INT NULL COMMENT 'status(状态0，删除1，正常）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '招聘者职位表';


-- -----------------------------------------------------
-- Table `db_boss`.`pp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`pp` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  `sp_id` INT NULL COMMENT '系统职位3级id',
  `p_id` INT NULL COMMENT '职位id',
  `createtime` DATETIME NULL COMMENT '创建时间',
  `updatetime` DATETIME NULL COMMENT '更新时间',
  `status` INT NULL COMMENT '状态0.删除1.正常',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_boss`.`user_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`user_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL,
  `createtime` DATETIME NULL,
  `type` VARCHAR(45) NULL COMMENT '类型 add、update、delete',
  `decription` VARCHAR(200) NULL COMMENT '详情描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户日志表';


-- -----------------------------------------------------
-- Table `db_boss`.`interview_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`interview_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL,
  `createtime` DATETIME NULL,
  `type` VARCHAR(45) NULL COMMENT '类型 add、update、delete',
  `decription` VARCHAR(200) NULL COMMENT '详情描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '面试日志表';


-- -----------------------------------------------------
-- Table `db_boss`.`position_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`position_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL,
  `createtime` DATETIME NULL,
  `type` VARCHAR(45) NULL COMMENT '类型 add、update、delete',
  `decription` VARCHAR(200) NULL COMMENT '详情描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '职位日志表';


-- -----------------------------------------------------
-- Table `db_boss`.`recruit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_boss`.`recruit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NULL,
  `createtime` DATETIME NULL,
  `type` VARCHAR(45) NULL COMMENT '类型 add、update、delete',
  `decription` VARCHAR(200) NULL COMMENT '详情描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '招聘信息日志表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
